### PR TITLE
Remove call to _update_coils in __init__

### PR DESCRIPTION
**Pull request by MrYsLab**
The reason for this pull request is documented here: https://github.com/adafruit/Adafruit_CircuitPython_Crickit/issues/17.

### CODE REVIEW

**Comment by ladyada** [comment]
awesome, thank you! could you verify it still works with stepper motors as expected?

**Comment by MrYsLab** [comment]
Yes, and it works if I install dc motors or a stepper. Tested on a Raspberry PI 3B+

**Comment by ladyada** [comment]
rad, thanks - the tests no longer pass because they assume that the coils start energized. if you are up for updating those as well, then when it passes we can merge it

**Comment by MrYsLab** [comment]
I am not able to run the tests in my environment but looking at the Travis output, it appears what needs to be done is to remove the following lines from each test:
```
for j in range(4):
    assert coil[j].duty_cycle == (0xffff if j == 0 else 0)
```

If that is correct, I can edit the test-file but want to make sure that is all that needs to be done and that I don't create havoc by doing so. Just let me know if you wish me to do that.

**Comment by ladyada** [comment]
i think maybe you want to perform a step - im not sure to be honest. you can leave it and when someone has a chance they can try fixing the test code up

**Comment by MrYsLab** [comment]
Sounds good to me. Tnx.

**Comment by makermelissa** [comment]
One option you could do is place an additional parameter into the init with a default of True, such as `init_coils=True` which would call `_update_coils` if True. You could override the default behavior by passing `init_coils=False` into your constructor and the tests should pass without modification.

**Comment by ladyada** [comment]
im ok with them not activating at first until the first step, id rather do that and stick with the decision than make it optional (and confusing?)

**Comment by makermelissa** [comment]
Ok, makes sense. That'll work then.

**Comment by ladyada** [comment]
wanna take a look at fixing the asserts at your convience?

**Comment by makermelissa** [comment]
Yep :)

**Comment by makermelissa** [comment]
Ok, it turns out uninitialized they should return all zeros, so I adjusted the asserts to compare against that.

**Comment by MrYsLab** [comment]
Thank you.

**Comment by tannewt** [comment]
I'm rolling this back. The library isn't designed to use when something else is connected.

More details here: https://github.com/adafruit/Adafruit_CircuitPython_Crickit/issues/17#issuecomment-497815843

**Pull request merged**
