### PR TITLE
renamed files

### PR DESCRIPTION
**Pull request by williamlai2**
from here: https://github.com/adafruit/Adafruit_CircuitPython_Motor/issues/31

### CODE REVIEW

**Review by kattni — CHANGES_REQUESTED** [review]
Thank you for picking this up! 

The only example that I wanted renamed as `motor_servo_sweep.py`. The others should be left as they were. Please return the four you renamed to their original names, and rename `motor_servo_sweep.py` to `motor_servo_sweep_simpletest.py`.

As well, you'll need to update the `examples.rst` file in the docs/ folder (/docs/examples.rst) to reflect the  name change:
```
Simple tests
-------------

Ensure your device works with this simple test.

.. literalinclude:: ../examples/motor_servo_sweep.py
    :caption: examplesmotor_servo_sweep.py
    :linenos:
```
Will need to be:
```
Simple tests
-------------

Ensure your device works with this simple test.

.. literalinclude:: ../examples/motor_servo_sweep_simpletest.py
    :caption: examples/motor_servo_sweep_simpletest.py
    :linenos:
```

**Comment by williamlai2** [comment]
I have updated those files. I had to re-upload the 'examples' folder as it disappeared from the branch, but it is the same as before, just renamed.

**Review by kattni — CHANGES_REQUESTED** [review]
Thank you for the update. The build is still failing due to all of the line endings in the examples you re-uploaded having CRLF line-endings vs the original LF line-endings. 

Unfortunately I think the best option may be to close this PR, and create a new one with only the necessary changes included. I apologise for the inconvenience, but I think that route will be the simplest vs trying to fix all the example code manually.

Please let me know if you have any questions or need assistance with that.

**Comment by williamlai2** [comment]
Sorry about that. I will close it and try again.

**Comment by kattni** [comment]
Closing in favor of #33

**Comment by williamlai2** [comment]
Thanks for the advice. I learnt quite a bit in doing this.

**Pull request closed without merging**
