### PR TITLE
Revert "Merge pull request #23 from plamponi/pwm_freq"

### PR DESCRIPTION
**Pull request by siddacious**
This reverts commit a8894480283e3b81f39a3db5716b443963abc56f, reversing
changes made to 7f93c2addf52a4f2d1a969bd83593b335a392e77.

(https://github.com/adafruit/Adafruit_CircuitPython_Crickit/issues/15)

### CODE REVIEW

**Comment by caternuson** [comment]
This will go back to what used to work. But what about the motivation for #23 ? Are we fixing stepper but bringing back that issue?

**Comment by siddacious** [comment]
I like the update in #23 and it's still a good idea however we should first make sure it's not breaking anything else. Until the issue with how this lib interacts with that feature is fixed I think trading it for having steppers working is OK.

**Comment by siddacious** [comment]
I'm not sure what the correct process is but we should either re-open #23 or create a new issue to re-do it with the fixes needed (I'm leaning towards a new issue)

@kattni Any thoughts on the best process to proceed?

**Comment by kattni** [comment]
Create a new issue and a new PR, please.

**Comment by ladyada** [comment]
thanx!

**Pull request merged**
