### PR TITLE
Add functionality for manually setting pulse width

### LINKED ISSUE #41: Add method to manually set pulse width
On the Arduino, the writeMicroseconds method of the Servo class is useful for calibrating servos that don't align directly with the 1-2ms range. An equivalent function or field in the servo class would be more convenient than setting the pulse width range to a wide value and calculating the actual limits.

### PR DESCRIPTION
**Pull request by tekktrik**
Picked up where #42 left off, addressing the remaining comments and adding an example file.  Not tested, but did my best to emulate the example based of the issue that spawned this.  Would resolve #41.

Tagging @tannewt who reviewed last.

### CODE REVIEW

**Comment by tannewt** [comment]
Are you setup to build CircuitPython? I'd want to test this in the CPX build to ensure it doesn't run out of memory. That was my main concern on the original PR.

**Comment by tekktrik** [comment]
Just built it successfully, though I didn't see it mention that it was freezing this library...

```
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
mkdir -p build-circuitplayground_express/genhdr
GEN build-circuitplayground_express/genhdr/moduledefs.h
QSTR updated
FREEZE ../../frozen/Adafruit_CircuitPython_CircuitPlayground ../../frozen/Adafruit_CircuitPython_HID ../../frozen/Adafruit_CircuitPython_LIS3DH ../../frozen/Adafruit_CircuitPython_NeoPixel ../../frozen/Adafruit_CircuitPython_Thermistor
MKMANIFEST ../../frozen/Adafruit_CircuitPython_CircuitPlayground ../../frozen/Adafruit_CircuitPython_HID ../../frozen/Adafruit_CircuitPython_LIS3DH ../../frozen/Adafruit_CircuitPython_NeoPixel ../../frozen/Adafruit_CircuitPython_Thermistor
(cd build-circuitplayground_express/frozen_mpy && find * -name \*.py -exec printf 'freeze_as_mpy("frozen_mpy", "%s")\n' {} \; )> build-circuitplayground_express/manifest.py.tmp && mv -f build-circuitplayground_express/manifest.py.tmp build-circuitplayground_express/manifest.py
MPY adafruit_circuitplayground/__init__.py
MPY adafruit_circuitplayground/bluefruit.py
MPY adafruit_circuitplayground/express.py
MPY adafruit_circuitplayground/circuit_playground_base.py
MPY adafruit_hid/__init__.py
MPY adafruit_hid/consumer_control_code.py
MPY adafruit_hid/consumer_control.py
MPY adafruit_hid/keyboard_layout_base.py
MPY adafruit_hid/mouse.py
MPY adafruit_hid/keycode.py
MPY adafruit_hid/keyboard_layout_us.py
MPY adafruit_hid/keyboard.py
MPY adafruit_lis3dh.py
MPY adafruit_thermistor.py
MPY neopixel.py
GEN build-circuitplayground_express/frozen_content.c

250812 bytes used, 2628 bytes free in flash firmware space out of 253440 bytes (247.5kB).
11824 bytes used, 20944 bytes free in ram for stack and heap out of 32768 bytes (32.0kB).
```

**Comment by tekktrik** [comment]
That's the Russian translation, by the way

**Comment by tekktrik** [comment]
Should I test it on Crickit?

**Comment by tekktrik** [comment]
If so, it looks like it takes up too much memory in the Russian translation:

```
253728 bytes used, -288 bytes free in flash firmware space out of 253440 bytes (247.5kB).
11824 bytes used, 20944 bytes free in ram for stack and heap out of 32768 bytes (32.0kB).
```

**Comment by tekktrik** [comment]
Is it worth closing both the issue and PR in this case?

**Comment by tannewt** [comment]
> Is it worth closing both the issue and PR in this case?

My opinion is that the direct pulse time setting isn't worth the extra space. Motor is meant to abstract it out. If folks don't want it abstracted out or abstracted in a different way, then they could use a lower or different library.

Maybe a separate PWM pulse time library would be simpler.

So, yes my vote would be to close both.

**Comment by tekktrik** [comment]
I agree, I'll close both.  Thanks for the review!

**Pull request closed without merging**
