### PR TITLE
Add Type Hints

### PR DESCRIPTION
**Pull request by tekktrik**
Address #56

### CODE REVIEW

**Comment by tekktrik** [comment]
Not sure why it fails on building the Sphinx docs... happy to change it with some help :)

**Comment by tekktrik** [comment]
Added pwmio to autodoc_mock_import in docs/conf.py so it would build, but want to make sure that's the correct solution

**Comment by dhalbert** [comment]
> Added pwmio to autodoc_mock_import in docs/conf.py so it would build, but want to make sure that's the correct solution

I think that makes sense here. `pwmio.PWMOut` is implemented for some boards under blinka, but not for "generic linux".

**Comment by tekktrik** [comment]
Awesome, thanks!

**Comment by tekktrik** [comment]
I don't see CircuitPythonLibrarians tagged, do I need that so this doesn't get lost?  Not too familiar with the review process behind-the-scenes.

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. did not test with hardware.

**Pull request merged**
